export enum NodeEnv {
  DEV = 'DEV',
  TEST = 'TEST',
  PROD = 'PROD'
}

export enum Env {
  NODE_ENV = 'NODE_ENV',
  THROTTLE_TTL = 'THROTTLE_TTL',
  THROTTLE_LIMIT = 'THROTTLE_LIMIT',
  AUTH_COOKIE_NAME = 'AUTH_COOKIE_NAME',
  AUTH_COOKIE_DOMAIN = 'AUTH_COOKIE_DOMAIN',
  HOST = 'HOST',
  PORT = 'PORT',
  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_NAME = 'DB_NAME',
  DB_USERNAME = 'DB_USERNAME',
  DB_PASSWORD = 'DB_PASSWORD'
}
